#pragma once

#include "Define.h"

#include "Algorithm/CurveSpanIntersection.h"
#include "Algorithm/CurveTessellation.h"
#include "Algorithm/KnotRefinement.h"
#include "Algorithm/NurbsCurveShapeFunction.h"
#include "Algorithm/NurbsSurfaceShapeFunction.h"
#include "Algorithm/PolygonTessellation.h"
#include "Algorithm/TrimmedSurfaceClipping.h"
#include "Geometry/Curve.h"
#include "Geometry/CurveBase.h"
#include "Geometry/CurveOnSurface.h"
#include "Geometry/Interval.h"
#include "Geometry/NurbsCurveGeometry.h"
#include "Geometry/NurbsSurfaceGeometry.h"
#include "Geometry/Polygon.h"
#include "Geometry/Surface.h"
#include "Geometry/SurfaceBase.h"

#include "src/IntegrationPoints.h"
#include "src/PointOnBrepProjection.h"
#include "src/PointOnCurveProjection.h"
#include "src/PointOnSurfaceProjection.h"
#include "src/PolygonIntegrationPoints.h"
